Repository JECT-Study/Componote-BE-WAS, pull requests merged in 2025-01, with the labels that each got.

#3 J01 10 be 댓글 기능
  src/main/java/ject/componote/domain/comment/api/CommentController.java
  src/main/java/ject/componote/domain/comment/application/CommentCreationStrategy.java
  src/main/java/ject/componote/domain/comment/application/CommentLikeEventListener.java
  src/main/java/ject/componote/domain/comment/application/CommentReplyCountEventHandler.java
  src/main/java/ject/componote/domain/comment/application/CommentService.java
  src/main/java/ject/componote/domain/comment/dao/CommentFindByComponentDao.java
  src/main/java/ject/componote/domain/comment/dao/CommentFindByMemberDao.java
  src/main/java/ject/componote/domain/comment/dao/CommentFindByParentDao.java
  src/main/java/ject/componote/domain/comment/dao/CommentLikeRepository.java
  src/main/java/ject/componote/domain/comment/dao/CommentProfileDao.java
  src/main/java/ject/componote/domain/comment/dao/CommentQueryDsl.java
  src/main/java/ject/componote/domain/comment/dao/CommentQueryDslImpl.java
  src/main/java/ject/componote/domain/comment/dao/CommentRepository.java
  src/main/java/ject/componote/domain/comment/dao/QCommentDaoFactory.java
  src/main/java/ject/componote/domain/comment/domain/Comment.java
  src/main/java/ject/componote/domain/comment/domain/CommentLike.java
  src/main/java/ject/componote/domain/comment/domain/CommentRepository.java
  src/main/java/ject/componote/domain/comment/dto/create/request/CommentCreateRequest.java
  src/main/java/ject/componote/domain/comment/dto/create/response/CommentCreateResponse.java
  src/main/java/ject/componote/domain/comment/dto/find/response/CommentFindByComponentResponse.java
  src/main/java/ject/componote/domain/comment/dto/find/response/CommentFindByMemberResponse.java
  src/main/java/ject/componote/domain/comment/dto/find/response/CommentFindByParentResponse.java
  src/main/java/ject/componote/domain/comment/dto/find/response/CommentProfileResponse.java
  src/main/java/ject/componote/domain/comment/dto/like/event/CommentLikeEvent.java
  src/main/java/ject/componote/domain/comment/dto/like/event/CommentUnlikeEvent.java
  src/main/java/ject/componote/domain/comment/dto/reply/event/CommentReplyCountIncreaseEvent.java
  src/main/java/ject/componote/domain/comment/dto/update/request/CommentUpdateRequest.java
  src/main/java/ject/componote/domain/comment/error/AlreadyLikedException.java
  src/main/java/ject/componote/domain/comment/error/BlankCommentException.java
  src/main/java/ject/componote/domain/comment/error/CommentException.java
  src/main/java/ject/componote/domain/comment/error/ExceedCommentLengthException.java
  src/main/java/ject/componote/domain/comment/error/InvalidCommentContentException.java
  src/main/java/ject/componote/domain/comment/error/InvalidCommentCreateStrategyException.java
  src/main/java/ject/componote/domain/comment/error/InvalidCommentImageExtensionException.java
  src/main/java/ject/componote/domain/comment/error/NoLikedException.java
  src/main/java/ject/componote/domain/comment/error/NotFoundCommentException.java
  src/main/java/ject/componote/domain/comment/error/NotFoundParentCommentException.java
  src/main/java/ject/componote/domain/comment/error/OffensiveCommentException.java
  src/main/java/ject/componote/domain/comment/model/CommentContent.java
  src/main/java/ject/componote/domain/comment/model/CommentImage.java
  src/main/java/ject/componote/domain/comment/model/converter/CommentImageConverter.java
  src/main/java/ject/componote/domain/comment/validation/CommenterValidation.java
  src/main/java/ject/componote/domain/comment/validation/CommenterValidationAspect.java
  src/main/java/ject/componote/domain/common/dto/response/PageResponse.java
  src/main/java/ject/componote/domain/common/model/Count.java
  src/main/java/ject/componote/domain/component/domain/block/detail/ImageBlock.java
  src/main/java/ject/componote/domain/component/domain/block/detail/TextBlock.java
  src/main/java/ject/componote/domain/component/domain/summary/ComponentSummary.java
  src/main/java/ject/componote/global/config/AsyncConfig.java
  src/main/java/ject/componote/global/config/QueryDslConfig.java
  src/main/java/ject/componote/global/util/RepositoryUtils.java
  src/main/java/ject/componote/infra/file/application/FileClient.java
  src/test/java/ject/componote/domain/comment/application/CommentCreationStrategyTest.java
  src/test/java/ject/componote/domain/comment/application/CommentLikeEventListenerTest.java
  src/test/java/ject/componote/domain/comment/application/CommentServiceTest.java
  src/test/java/ject/componote/domain/comment/model/CommentContentTest.java
  src/test/java/ject/componote/domain/comment/model/CommentImageTest.java
  src/test/java/ject/componote/domain/comment/validation/CommenterValidationAspectTest.java
  src/test/java/ject/componote/fixture/CommentFixture.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🗂️db

#2 J01 2 be 북마크 작업
  src/main/java/ject/componote/domain/bookmark/api/BookmarkController.java
  src/main/java/ject/componote/domain/bookmark/application/BookmarkService.java
  src/main/java/ject/componote/domain/bookmark/domain/Bookmark.java
  src/main/java/ject/componote/domain/bookmark/domain/BookmarkRepository.java
  src/main/java/ject/componote/domain/bookmark/dto/request/BookmarkRequest.java
  src/main/java/ject/componote/domain/bookmark/dto/response/BookmarkResponse.java
  src/main/java/ject/componote/domain/bookmark/error/BookmarkException.java
  src/main/java/ject/componote/domain/bookmark/error/ExistedBookmarkError.java
  src/main/java/ject/componote/domain/bookmark/error/ExistedComponentError.java
  src/main/java/ject/componote/domain/bookmark/error/InvalidBookmarkTypeError.java
  src/main/java/ject/componote/domain/bookmark/error/NotFoundBookmarkException.java
  src/main/java/ject/componote/domain/bookmark/error/NotFoundComponentException.java
  src/main/java/ject/componote/domain/bookmark/error/NotFoundDesignSystemException.java
  src/main/java/ject/componote/domain/bookmark/error/NotFoundMemberException.java
  src/main/java/ject/componote/domain/component/domain/ComponentRepository.java
  src/main/java/ject/componote/domain/design/domain/DesignSystemRepository.java
  src/test/java/ject/componote/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/ject/componote/fixture/BookmarkFixture.java
  src/test/java/ject/componote/fixture/ComponentFixture.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#7 J01 44 be 디자인 시스템 사진 엔티티 변경
  src/main/java/ject/componote/domain/bookmark/application/BookmarkService.java
  src/main/java/ject/componote/domain/design/application/DesignSystemService.java
  src/main/java/ject/componote/domain/design/dao/DesignRepository.java
  src/main/java/ject/componote/domain/design/dao/DesignSystemRepository.java
  src/main/java/ject/componote/domain/design/dao/filter/DesignFilterRepository.java
  src/main/java/ject/componote/domain/design/dao/link/DesignLinkRepository.java
  src/main/java/ject/componote/domain/design/domain/DesignPhoto.java
  src/main/java/ject/componote/domain/design/error/DesignException.java
  src/main/java/ject/componote/domain/design/error/InvalidDesignPhotoImageExtensionException.java
  src/main/java/ject/componote/domain/design/error/NotFoundDesignPhotoImageException.java
  src/main/java/ject/componote/domain/design/model/DesignPhotoImage.java
  src/main/java/ject/componote/domain/design/model/converter/DesignPhotoImageConverter.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🪄refactor

#8 J01 45 be 회원 기능 수정
  src/main/java/ject/componote/domain/auth/api/MemberController.java
  src/main/java/ject/componote/domain/auth/application/MemberService.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#9 J01 51 be 이메일 인증
  src/main/java/ject/componote/domain/auth/api/AuthController.java
  src/main/java/ject/componote/domain/auth/api/MemberController.java
  src/main/java/ject/componote/domain/auth/application/AuthService.java
  src/main/java/ject/componote/domain/auth/application/MemberService.java
  src/main/java/ject/componote/domain/auth/dao/MemberRepository.java
  src/main/java/ject/componote/domain/auth/dao/MemberSummaryDao.java
  src/main/java/ject/componote/domain/auth/domain/Member.java
  src/main/java/ject/componote/domain/auth/dto/find/response/MemberSummaryResponse.java
  src/main/java/ject/componote/domain/auth/dto/update/request/MemberEmailUpdateRequest.java
  src/main/java/ject/componote/domain/auth/dto/validate/request/MemberEmailValidateRequest.java
  src/main/java/ject/componote/domain/auth/dto/verify/request/MemberEmailVerificationRequest.java
  src/main/java/ject/componote/domain/auth/error/DuplicatedEmailException.java
  src/main/java/ject/componote/domain/auth/error/SameEmailUpdateException.java
  src/main/java/ject/componote/global/error/GlobalExceptionHandler.java
  src/main/java/ject/componote/infra/mail/application/MailService.java
  src/main/java/ject/componote/infra/mail/config/MailConfig.java
  src/main/java/ject/componote/infra/mail/error/EmailMessageCreationException.java
  src/main/java/ject/componote/infra/mail/error/MailException.java
  src/main/java/ject/componote/infra/mail/error/NotFoundVerificationCodeException.java
  src/main/java/ject/componote/infra/mail/model/VerificationCode.java
  src/main/java/ject/componote/infra/mail/repository/VerificationCodeRepository.java
  src/main/java/ject/componote/infra/mail/repository/impl/InMemoryVerificationCodeRepository.java
  src/main/java/ject/componote/infra/mail/util/MailTemplateProvider.java
  src/main/java/ject/componote/infra/mail/util/VerificationCodeProvider.java
  src/test/java/ject/componote/domain/auth/application/MemberServiceTest.java
  src/test/java/ject/componote/infra/mail/application/MailServiceTest.java
  src/test/java/ject/componote/infra/mail/repository/impl/InMemoryVerificationCodeRepositoryTest.java
  src/test/java/ject/componote/infra/mail/util/MailTemplateProviderTest.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#11 J01 58 be 알림 기능
  .gitignore
  src/main/java/ject/componote/domain/auth/domain/Member.java
  src/main/java/ject/componote/domain/comment/api/CommentController.java
  src/main/java/ject/componote/domain/comment/api/CommentLikeController.java
  src/main/java/ject/componote/domain/comment/application/CommentLikeEventListener.java
  src/main/java/ject/componote/domain/comment/application/CommentLikeNotificationEventListener.java
  src/main/java/ject/componote/domain/comment/application/CommentLikeService.java
  src/main/java/ject/componote/domain/comment/application/CommentReplyCountEventHandler.java
  src/main/java/ject/componote/domain/comment/application/CommentReplyNotificationEventListener.java
  src/main/java/ject/componote/domain/comment/application/CommentService.java
  src/main/java/ject/componote/domain/comment/dao/CommentQueryDsl.java
  src/main/java/ject/componote/domain/comment/dao/CommentQueryDslImpl.java
  src/main/java/ject/componote/domain/comment/domain/Comment.java
  src/main/java/ject/componote/domain/comment/dto/like/event/CommentLikeNotificationEvent.java
  src/main/java/ject/componote/domain/comment/dto/reply/event/CommentReplyCountIncreaseEvent.java
  src/main/java/ject/componote/domain/comment/dto/reply/event/CommentReplyNotificationEvent.java
  src/main/java/ject/componote/infra/config/RabbitMqConfig.java
  src/main/java/ject/componote/infra/file/dto/move/response/MoveResponse.java
  src/main/java/ject/componote/infra/notification/application/NotificationProducer.java
  src/main/java/ject/componote/infra/notification/dto/create/request/CommentLikeNotificationCreateRequest.java
  src/main/java/ject/componote/infra/notification/dto/create/request/NestedReplyNotificationCreateRequest.java
  src/main/java/ject/componote/infra/notification/dto/create/request/NoticeNotificationCreateRequest.java
  src/main/java/ject/componote/infra/notification/dto/create/request/NotificationParticipant.java
  src/main/java/ject/componote/infra/notification/dto/create/request/RootReplyNotificationCreateRequest.java
  src/test/java/ject/componote/domain/comment/application/CommentLikeNotificationEventListenerTest.java
  src/test/java/ject/componote/domain/comment/application/CommentLikeServiceTest.java
  src/test/java/ject/componote/domain/comment/application/CommentServiceTest.java
  src/test/java/ject/componote/fixture/MemberFixture.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#14 J01 59 be 이미지 경로 변경 api 통신 방식 수정
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/ject/componote/domain/auth/application/AuthService.java
  src/main/java/ject/componote/domain/auth/application/MemberService.java
  src/main/java/ject/componote/domain/comment/application/CommentService.java
  src/main/java/ject/componote/domain/comment/domain/Comment.java
  src/main/java/ject/componote/global/error/GlobalExceptionHandler.java
  src/main/java/ject/componote/infra/file/application/FileClient.java
  src/main/java/ject/componote/infra/file/application/FileService.java
  src/main/java/ject/componote/infra/file/dto/move/request/MoveRequest.java
  src/main/java/ject/componote/infra/file/error/FileClientException.java
  src/main/java/ject/componote/infra/file/error/FileServerErrorResponse.java
  src/main/java/ject/componote/infra/storage/application/StorageProducer.java
  src/main/java/ject/componote/infra/storage/application/StorageService.java
  src/main/java/ject/componote/infra/storage/dto/move/request/ImageMoveRequest.java
  src/test/java/ject/componote/domain/auth/application/AuthServiceTest.java
  src/test/java/ject/componote/domain/auth/application/MemberServiceTest.java
  src/test/java/ject/componote/domain/comment/application/CommentLikeEventListenerTest.java
  src/test/java/ject/componote/domain/comment/application/CommentServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#15 J01 64 be 컴포넌트 엔티티 수정
  src/main/java/ject/componote/domain/common/model/AbstractImage.java
  src/main/java/ject/componote/domain/component/application/ComponentSearchStrategy.java
  src/main/java/ject/componote/domain/component/application/ComponentService.java
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDsl.java
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDslImpl.java
  src/main/java/ject/componote/domain/component/dao/ComponentRepository.java
  src/main/java/ject/componote/domain/component/dao/QComponentDaoFactory.java
  src/main/java/ject/componote/domain/component/domain/Component.java
  src/main/java/ject/componote/domain/component/domain/block/BlockType.java
  src/main/java/ject/componote/domain/component/domain/block/ContentBlock.java
  src/main/java/ject/componote/domain/component/domain/block/detail/ImageBlock.java
  src/main/java/ject/componote/domain/component/domain/block/detail/TextBlock.java
  src/main/java/ject/componote/domain/component/domain/summary/ComponentSummary.java
  src/main/java/ject/componote/domain/component/dto/find/request/ComponentSearchRequest.java
  src/main/java/ject/componote/domain/component/dto/find/response/ComponentDetailResponse.java
  src/main/java/ject/componote/domain/component/dto/find/response/ComponentSummaryResponse.java
  src/main/java/ject/componote/domain/component/util/ComponentMapper.java
  src/main/java/ject/componote/global/error/GlobalExceptionHandler.java
  src/test/java/ject/componote/domain/component/application/ComponentSearchStrategyTest.java
  src/test/java/ject/componote/domain/component/application/ComponentServiceTest.java
  src/test/java/ject/componote/domain/component/util/ComponentMapperTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#16 J01 65 be 회원 가입 응답 수정
  src/main/java/ject/componote/domain/auth/application/AuthService.java
  src/main/java/ject/componote/domain/auth/dto/signup/response/MemberSignupResponse.java
  src/test/java/ject/componote/domain/auth/application/AuthServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#17 1.1차 배포
  src/main/java/ject/componote/domain/auth/application/AuthService.java
  src/main/java/ject/componote/domain/auth/application/MemberService.java
  src/main/java/ject/componote/domain/auth/dto/signup/response/MemberSignupResponse.java
  src/main/java/ject/componote/domain/comment/application/CommentService.java
  src/main/java/ject/componote/domain/common/model/AbstractImage.java
  src/main/java/ject/componote/domain/component/application/ComponentSearchStrategy.java
  src/main/java/ject/componote/domain/component/application/ComponentService.java
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDsl.java
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDslImpl.java
  src/main/java/ject/componote/domain/component/dao/ComponentRepository.java
  src/main/java/ject/componote/domain/component/dao/QComponentDaoFactory.java
  src/main/java/ject/componote/domain/component/domain/Component.java
  src/main/java/ject/componote/domain/component/domain/block/BlockType.java
  src/main/java/ject/componote/domain/component/domain/block/ContentBlock.java
  src/main/java/ject/componote/domain/component/domain/block/detail/ImageBlock.java
  src/main/java/ject/componote/domain/component/domain/block/detail/TextBlock.java
  src/main/java/ject/componote/domain/component/domain/summary/ComponentSummary.java
  src/main/java/ject/componote/domain/component/dto/find/request/ComponentSearchRequest.java
  src/main/java/ject/componote/domain/component/dto/find/response/ComponentDetailResponse.java
  src/main/java/ject/componote/domain/component/dto/find/response/ComponentSummaryResponse.java
  src/main/java/ject/componote/domain/component/util/ComponentMapper.java
  src/main/java/ject/componote/global/error/GlobalExceptionHandler.java
  src/main/java/ject/componote/infra/file/application/FileClient.java
  src/main/java/ject/componote/infra/file/application/FileService.java
  src/main/java/ject/componote/infra/file/dto/move/request/MoveRequest.java
  src/main/java/ject/componote/infra/file/error/FileClientException.java
  src/main/java/ject/componote/infra/file/error/FileServerErrorResponse.java
  src/main/java/ject/componote/infra/storage/application/StorageProducer.java
  src/main/java/ject/componote/infra/storage/application/StorageService.java
  src/main/java/ject/componote/infra/storage/dto/move/request/ImageMoveRequest.java
  src/test/java/ject/componote/domain/auth/application/AuthServiceTest.java
  src/test/java/ject/componote/domain/auth/application/MemberServiceTest.java
  src/test/java/ject/componote/domain/comment/application/CommentLikeEventListenerTest.java
  src/test/java/ject/componote/domain/comment/application/CommentServiceTest.java
  src/test/java/ject/componote/domain/component/application/ComponentSearchStrategyTest.java
  src/test/java/ject/componote/domain/component/application/ComponentServiceTest.java
  src/test/java/ject/componote/domain/component/util/ComponentMapperTest.java
Labels: 👨🏻‍💻backend, 💻server
