Repository JECT-Study/Componote-BE-WAS, pull requests merged in 2025-02, with the labels that each got.

#10 J01 2 be 북마크 작업
  src/main/java/ject/componote/domain/bookmark/api/BookmarkController.java
  src/main/java/ject/componote/domain/bookmark/api/ComponentBookmarkController.java
  src/main/java/ject/componote/domain/bookmark/api/DesignBookmarkController.java
  src/main/java/ject/componote/domain/bookmark/application/BookmarkService.java
  src/main/java/ject/componote/domain/bookmark/dao/ComponentBookmarkRepository.java
  src/main/java/ject/componote/domain/bookmark/dao/DesignBookmarkRepository.java
  src/main/java/ject/componote/domain/bookmark/domain/ComponentBookmark.java
  src/main/java/ject/componote/domain/bookmark/domain/DesignBookmark.java
  src/main/java/ject/componote/domain/bookmark/dto/response/BookmarkResponse.java
  src/main/java/ject/componote/domain/bookmark/dto/response/ComponentBookmarkResponse.java
  src/main/java/ject/componote/domain/bookmark/dto/response/DesignBookmarkResponse.java
  src/test/java/ject/componote/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/ject/componote/fixture/BookmarkFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#13 J01 41 be 디자인 시스템 기능
  src/main/java/ject/componote/domain/design/api/DesignSystemController.java
  src/main/java/ject/componote/domain/design/application/DesignSystemService.java
  src/main/java/ject/componote/domain/design/dao/DesignRepository.java
  src/main/java/ject/componote/domain/design/dao/DesignSystemRepository.java
  src/main/java/ject/componote/domain/design/dto/search/response/DesignLinkResponse.java
  src/main/java/ject/componote/domain/design/dto/search/response/DesignSystemSearchResponse.java
  src/main/java/ject/componote/domain/design/error/NotFoundDesignException.java
  src/main/java/ject/componote/domain/design/error/NotFoundDesignPhotoImageException.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#22 J01 41 be 디자인 시스템 기능
  src/main/java/ject/componote/domain/design/application/DesignSystemService.java
  src/main/java/ject/componote/domain/design/dao/DesignSystemRepository.java
  src/main/java/ject/componote/domain/design/dto/search/response/DesignSystemSearchResponse.java
  src/test/java/ject/componote/domain/design/DesignSystemServiceTest.java
  src/test/java/ject/componote/fixture/DesignFixture.java
Labels: 👨🏻‍💻backend

#20 J01 91 be 컴포넌트 검색 페이지네이션 오류 수정
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDslImpl.java
  src/main/java/ject/componote/global/util/RepositoryUtils.java
Labels: ✔︎pull requests, 🐛bug, 🪄refactor

#21 J01 93 be 닉네임 검증 예외 메시지 세분화
  src/main/java/ject/componote/domain/auth/error/InvalidNicknameCharacterException.java
  src/main/java/ject/componote/domain/auth/error/InvalidNicknameException.java
  src/main/java/ject/componote/domain/auth/error/InvalidNicknameLengthException.java
  src/main/java/ject/componote/domain/auth/error/OffensiveNicknameException.java
  src/main/java/ject/componote/domain/auth/model/Nickname.java
  src/test/java/ject/componote/domain/auth/model/NicknameTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#23 1.3차 배포
  src/main/java/ject/componote/domain/auth/error/InvalidNicknameCharacterException.java
  src/main/java/ject/componote/domain/auth/error/InvalidNicknameException.java
  src/main/java/ject/componote/domain/auth/error/InvalidNicknameLengthException.java
  src/main/java/ject/componote/domain/auth/error/OffensiveNicknameException.java
  src/main/java/ject/componote/domain/auth/model/Nickname.java
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDslImpl.java
  src/main/java/ject/componote/global/util/RepositoryUtils.java
  src/test/java/ject/componote/domain/auth/model/NicknameTest.java
Labels: 💻server

#24 J01 95 be 댓글 생성 로직에 누락된 기능 추가
  src/main/java/ject/componote/domain/comment/application/CommentImageEventListener.java
  src/main/java/ject/componote/domain/comment/application/CommentReplyCountEventListener.java
  src/main/java/ject/componote/domain/comment/application/CommentReportEventListener.java
  src/main/java/ject/componote/domain/comment/application/CommentService.java
  src/main/java/ject/componote/domain/comment/dao/CommentRepository.java
  src/main/java/ject/componote/domain/comment/dto/image/event/CommentImageMoveEvent.java
  src/main/java/ject/componote/domain/comment/error/NotFoundParentCommentException.java
  src/main/java/ject/componote/domain/component/application/ComponentCommentCountEventListener.java
  src/main/java/ject/componote/domain/component/application/ComponentService.java
  src/main/java/ject/componote/domain/component/application/ComponentViewCountEventListener.java
  src/main/java/ject/componote/domain/component/domain/Component.java
  src/main/java/ject/componote/domain/component/dto/event/ComponentCommentCountDecreaseEvent.java
  src/main/java/ject/componote/domain/component/dto/event/ComponentCommentCountIncreaseEvent.java
  src/main/java/ject/componote/domain/component/dto/event/ComponentViewCountIncreaseEvent.java
  src/test/java/ject/componote/domain/comment/application/CommentReplyCountEventListenerTest.java
  src/test/java/ject/componote/domain/comment/application/CommentServiceTest.java
  src/test/java/ject/componote/domain/component/application/ComponentServiceTest.java
  src/test/java/ject/componote/domain/component/application/ComponentViewCountEventListenerTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#27 J01 98 be 컴포넌트 검색 페이지네이션 오류 재수정
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDslImpl.java
  src/main/java/ject/componote/global/util/RepositoryUtils.java
Labels: ✔︎pull requests, 🐛bug, 👨🏻‍💻backend, 🪄refactor

#29 J01 41 be 필터링 오류 해결
  src/main/java/ject/componote/domain/design/application/DesignSystemService.java
  src/main/java/ject/componote/domain/design/dao/DesignSystemRepository.java
  src/main/java/ject/componote/domain/design/dto/search/request/DesignSystemSearchRequest.java
Labels: 👨🏻‍💻backend

#18 J01 68 be 소셜 로그인 응답값 암호화
  src/main/java/ject/componote/domain/auth/application/AuthService.java
  src/main/java/ject/componote/domain/auth/application/OAuthService.java
  src/main/java/ject/componote/domain/auth/dto/login/request/MemberLoginRequest.java
  src/main/java/ject/componote/domain/auth/dto/login/response/OAuthLoginResponse.java
  src/main/java/ject/componote/domain/auth/dto/signup/request/MemberSignupRequest.java
  src/main/java/ject/componote/domain/auth/error/DuplicatedSignupException.java
  src/main/java/ject/componote/domain/auth/error/NotFoundMemberException.java
  src/main/java/ject/componote/domain/auth/error/NotFoundSocialAccountException.java
  src/main/java/ject/componote/domain/auth/token/application/TokenService.java
  src/main/java/ject/componote/domain/auth/token/config/TokenConfig.java
  src/main/java/ject/componote/domain/auth/token/error/InvalidSocialAccountTokenException.java
  src/main/java/ject/componote/domain/auth/token/model/TokenAdapter.java
  src/main/java/ject/componote/domain/auth/token/model/TokenProperties.java
  src/main/java/ject/componote/domain/auth/token/model/TokenProvider.java
  src/main/java/ject/componote/domain/auth/token/model/TokenType.java
  src/main/java/ject/componote/domain/auth/token/repository/InMemoryTokenProviderRepository.java
  src/main/java/ject/componote/domain/auth/util/TokenProvider.java
  src/main/java/ject/componote/global/interceptor/AuthenticationInterceptor.java
  src/main/java/ject/componote/global/interceptor/MemberAuthorityInterceptor.java
  src/main/java/ject/componote/global/resolver/AuthPrincipalResolver.java
  src/test/java/ject/componote/domain/auth/application/AuthServiceTest.java
  src/test/java/ject/componote/domain/auth/application/OAuthServiceTest.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#32 J01 99 be 회원가입 프로필 이미지 핸들링 로직 수정
  src/main/java/ject/componote/domain/auth/application/AuthService.java
  src/main/java/ject/componote/domain/auth/application/MemberService.java
  src/main/java/ject/componote/domain/auth/application/ProfileImageEventListener.java
  src/main/java/ject/componote/domain/auth/dto/image/event/ProfileImageMoveEvent.java
  src/main/java/ject/componote/domain/auth/model/ProfileImage.java
  src/main/java/ject/componote/infra/storage/application/StorageService.java
  src/test/java/ject/componote/domain/auth/application/AuthServiceTest.java
  src/test/java/ject/componote/domain/auth/application/MemberServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#33 J01 102 be 인증 코드 메일 전송 로직 수정
  build.gradle
  src/main/java/ject/componote/domain/auth/application/MemberEmailVerificationEventListener.java
  src/main/java/ject/componote/domain/auth/application/MemberService.java
  src/main/java/ject/componote/domain/auth/application/VerificationCodeService.java
  src/main/java/ject/componote/domain/auth/dao/VerificationCodeRepository.java
  src/main/java/ject/componote/domain/auth/dao/impl/InMemoryVerificationCodeRepository.java
  src/main/java/ject/componote/domain/auth/domain/VerificationCode.java
  src/main/java/ject/componote/domain/auth/dto/verify/event/EmailVerificationCodeSendEvent.java
  src/main/java/ject/componote/domain/auth/error/NotFoundVerificationCodeException.java
  src/main/java/ject/componote/domain/auth/util/VerificationCodeProvider.java
  src/main/java/ject/componote/infra/config/RabbitMqConfig.java
  src/main/java/ject/componote/infra/mail/application/MailProducer.java
  src/main/java/ject/componote/infra/mail/application/MailService.java
  src/main/java/ject/componote/infra/mail/config/MailConfig.java
  src/main/java/ject/componote/infra/mail/dto/VerificationCodeMailRequest.java
  src/main/java/ject/componote/infra/mail/error/EmailMessageCreationException.java
  src/main/java/ject/componote/infra/mail/error/MailException.java
  src/main/java/ject/componote/infra/mail/util/MailTemplateProvider.java
  src/test/java/ject/componote/domain/auth/application/MemberServiceTest.java
  src/test/java/ject/componote/infra/mail/application/MailServiceTest.java
  src/test/java/ject/componote/infra/mail/repository/impl/InMemoryVerificationCodeRepositoryTest.java
  src/test/java/ject/componote/infra/mail/util/MailTemplateProviderTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#34 J01 41 be 링크가 출력 안되는 오류 해결
  src/main/java/ject/componote/domain/design/model/Url.java
  src/main/java/ject/componote/domain/design/model/converter/UrlConverter.java
Labels: ✔︎pull requests, 👨🏻‍💻backend

#35 J01 105 be 컴포넌트 네비게이션 바 api 추가
  src/main/java/ject/componote/domain/bookmark/dao/ComponentBookmarkQueryDsl.java
  src/main/java/ject/componote/domain/bookmark/dao/ComponentBookmarkQueryDslImpl.java
  src/main/java/ject/componote/domain/bookmark/dao/ComponentBookmarkRepository.java
  src/main/java/ject/componote/domain/component/api/ComponentController.java
  src/main/java/ject/componote/domain/component/application/ComponentService.java
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDsl.java
  src/main/java/ject/componote/domain/component/dao/ComponentQueryDslImpl.java
  src/main/java/ject/componote/domain/component/dao/ComponentSummaryDao.java
  src/main/java/ject/componote/domain/component/dao/QComponentDaoFactory.java
  src/main/java/ject/componote/domain/component/dto/find/request/ComponentSearchRequest.java
  src/main/java/ject/componote/domain/component/dto/find/request/ComponentSummaryRequest.java
  src/main/java/ject/componote/domain/component/dto/find/response/ComponentSearchResponse.java
  src/main/java/ject/componote/domain/component/dto/find/response/ComponentSummaryResponse.java
  src/main/java/ject/componote/domain/component/util/ComponentMapper.java
  src/test/java/ject/componote/domain/component/application/ComponentServiceTest.java
  src/test/java/ject/componote/domain/component/util/ComponentMapperTest.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend, 🪄refactor

#36 J01 41 be 추천순 정렬 추가
  src/main/java/ject/componote/domain/design/domain/Design.java
  src/main/java/ject/componote/domain/design/domain/summary/DesignSummary.java
  src/main/java/ject/componote/domain/design/dto/search/response/DesignSystemSearchResponse.java
Labels: ✔︎pull requests, ✨feature, 👨🏻‍💻backend

#40 J01 108 be 회원 정보 수정 api 통일
  src/main/java/ject/componote/domain/auth/api/MemberController.java
  src/main/java/ject/componote/domain/auth/application/MemberService.java
  src/main/java/ject/componote/domain/auth/domain/Member.java
  src/main/java/ject/componote/domain/auth/dto/update/request/MemberUpdateRequest.java
  src/test/java/ject/componote/domain/auth/application/MemberServiceTest.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#39 J01 41 be 디자인 시스템 썸네일 응답 추가
  src/main/java/ject/componote/domain/design/domain/Design.java
  src/main/java/ject/componote/domain/design/domain/summary/DesignSummary.java
  src/main/java/ject/componote/domain/design/dto/search/response/DesignSystemSearchResponse.java
  src/test/java/ject/componote/fixture/DesignFixture.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor

#44 J01 41 be 디자인 시스템 api 분리
  src/main/java/ject/componote/domain/design/api/DesignSystemController.java
  src/main/java/ject/componote/domain/design/application/DesignSystemService.java
  src/main/java/ject/componote/domain/design/dao/DesignSystemRepository.java
  src/main/java/ject/componote/domain/design/dto/search/request/DesignSystemSearchRequest.java
  src/main/java/ject/componote/domain/design/dto/search/request/DesignSystemSummaryRequest.java
  src/main/java/ject/componote/domain/design/dto/search/response/DesignSystemSearchResponse.java
  src/main/java/ject/componote/domain/design/dto/search/response/DesignSystemSummaryResponse.java
Labels: ✔︎pull requests, 👨🏻‍💻backend, 🪄refactor
